import { Link } from "react-router-dom";

export default function ConsumerResult() {
  const fileName =
    sessionStorage.getItem("consumerFileName") || "Product";

  const storedResult =
    sessionStorage.getItem("consumerResult");

  const result = storedResult
    ? JSON.parse(storedResult)
    : null;

  if (!result) {
    return (
      <div className="page consumer-page">
        <div className="consumer-empty-result">
          <h2>No analysis available</h2>
          <p>
            Please scan a food product first.
          </p>

          <Link
            to="/consumer"
            className="consumer-back-btn"
          >
            ← Analyse a product
          </Link>
        </div>
      </div>
    );
  }

  const health = result.health_assessment || {};
  const nutrition = result.nutrition || {};

  const ingredients = Array.isArray(result.ingredients)
    ? result.ingredients
    : [];

  const watchItems = Array.isArray(
    result.ingredients_to_watch
  )
    ? result.ingredients_to_watch
    : [];

  const alternatives = Array.isArray(
    result.alternatives
  )
    ? result.alternatives
    : [];

  const score =
    typeof health.score === "number"
      ? health.score
      : null;

  function assessmentLabel() {
    switch (health.label) {
      case "GENERALLY_BETTER":
        return "Generally Better";

      case "MIXED":
        return "Mixed";

      case "LIMIT":
        return "Consider Limiting";

      default:
        return "Insufficient Data";
    }
  }

  return (
    <div className="page consumer-result-page">

      {/* HEADER */}
      <div className="consumer-result-header">

        <div>
          <span className="eyebrow">
            CONSUMER • AI FOOD INTELLIGENCE
          </span>

          <h1>
            Food Analysis
          </h1>

          <p>
            Label-based insights generated by LabelMitra AI.
          </p>
        </div>

        <Link
          to="/consumer"
          className="consumer-back-btn"
        >
          ← Analyse another
        </Link>

      </div>


      {/* PRODUCT */}
      <div className="consumer-product-banner">

        <div className="consumer-product-icon">
          🥗
        </div>

        <div>
          <span>
            PRODUCT ANALYSED
          </span>

          <h2>
            {result.product_name || fileName}
          </h2>

          <p>
            Based on information visible on the uploaded label.
          </p>
        </div>

      </div>


      {/* HEALTH + NUTRITION */}
      <div className="consumer-result-grid">

        {/* HEALTH */}
        <section className="consumer-result-card health-score-card">

          <span>
            AI FOOD ASSESSMENT
          </span>

          <div className="health-score-circle">

            <strong>
              {score !== null ? score : "—"}
            </strong>

            {score !== null && (
              <small>
                /100
              </small>
            )}

          </div>

          <h3>
            {assessmentLabel()}
          </h3>

          <p>
            {health.summary ||
              "The available label information is not sufficient for a detailed assessment."}
          </p>


          {Array.isArray(health.reasons) &&
            health.reasons.length > 0 && (

              <div className="health-reasons">

                <strong>
                  Why?
                </strong>

                <ul>
                  {health.reasons
                    .slice(0, 3)
                    .map((reason, index) => (
                      <li key={index}>
                        {reason}
                      </li>
                    ))}
                </ul>

              </div>

            )}

        </section>


        {/* NUTRITION */}
        <section className="consumer-result-card">

          <span>
            NUTRITION SNAPSHOT
          </span>

          <h2>
            Nutrition
          </h2>

          <div className="nutrition-grid">

            <NutritionItem
              label="Serving Size"
              value={nutrition.serving_size}
            />

            <NutritionItem
              label="Calories"
              value={nutrition.calories}
            />

            <NutritionItem
              label="Protein"
              value={nutrition.protein}
            />

            <NutritionItem
              label="Carbohydrates"
              value={nutrition.carbohydrates}
            />

            <NutritionItem
              label="Sugars"
              value={nutrition.sugars}
            />

            <NutritionItem
              label="Fat"
              value={nutrition.fat}
            />

            <NutritionItem
              label="Saturated Fat"
              value={nutrition.saturated_fat}
            />

            <NutritionItem
              label="Fiber"
              value={nutrition.fiber}
            />

            <NutritionItem
              label="Sodium"
              value={nutrition.sodium}
            />

          </div>

        </section>

      </div>


      {/* INGREDIENTS */}
      <section className="consumer-section">

        <div className="consumer-section-header">

          <span>
            LABEL BREAKDOWN
          </span>

          <h2>
            Ingredients
          </h2>

          <p>
            Ingredients detected from the product label.
          </p>

        </div>


        {ingredients.length > 0 ? (

          <div className="ingredient-list">

            {ingredients.map(
              (ingredient, index) => (

                <span
                  className="ingredient-chip"
                  key={index}
                >
                  {ingredient}
                </span>

              )
            )}

          </div>

        ) : (

          <p>
            No visible ingredients were detected.
          </p>

        )}

      </section>


      {/* WATCH */}
      <section className="consumer-section">

        <div className="consumer-section-header">

          <span>
            PAY ATTENTION TO
          </span>

          <h2>
            Ingredients to Watch
          </h2>

          <p>
            Things consumers may want to pay attention to
            based on the visible label.
          </p>

        </div>


        {watchItems.length > 0 ? (

          <div className="watch-list">

            {watchItems
              .slice(0, 3)
              .map((item, index) => (

                <div
                  className="watch-item"
                  key={index}
                >

                  <span>
                    !
                  </span>

                  <p>
                    {item}
                  </p>

                </div>

              ))}

          </div>

        ) : (

          <p>
            No specific label-based factors were highlighted.
          </p>

        )}

      </section>


      {/* ALTERNATIVES */}
      <section className="consumer-section">

        <div className="consumer-section-header">

          <span>
            AI SUGGESTIONS
          </span>

          <h2>
            Better Alternatives
          </h2>

          <p>
            General alternative choices suggested by AI.
          </p>

        </div>


        {alternatives.length > 0 ? (

          <div className="alternative-grid">

            {alternatives
              .slice(0, 3)
              .map((alternative, index) => {

                const title =
                  typeof alternative === "string"
                    ? alternative
                    : alternative?.name ||
                      alternative?.title ||
                      "Alternative";

                const description =
                  typeof alternative === "string"
                    ? ""
                    : alternative?.reason ||
                      alternative?.description ||
                      "";

                return (
                  <div
                    className="alternative-card"
                    key={index}
                  >

                    <span className="alternative-number">
                      {String(index + 1).padStart(
                        2,
                        "0"
                      )}
                    </span>

                    <div>

                      <h3>
                        {title}
                      </h3>

                      {description && (
                        <p>
                          {description}
                        </p>
                      )}

                    </div>

                  </div>
                );
              })}

          </div>

        ) : (

          <p>
            No alternative suggestions available.
          </p>

        )}

      </section>


      {/* DISCLAIMER */}
      <div className="consumer-disclaimer">

        <strong>
          AI Insight:
        </strong>{" "}

        {result.disclaimer ||
          "General label-based information, not medical advice."}

      </div>

    </div>
  );
}


/* =========================================================
   NUTRITION ITEM
   ========================================================= */

function NutritionItem({
  label,
  value,
}) {
  return (
    <div className="nutrition-item">

      <span>
        {label}
      </span>

      <strong>
        {value !== null &&
        value !== undefined &&
        value !== ""
          ? value
          : "Not visible"}
      </strong>

    </div>
  );
}